{% set name = "pycsep" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycsep-{{ version }}.tar.gz
  sha256: 679c66696a60d03ccb808c0f3de5e0c2a41fca7f3c4af670fb9d992702a61d9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cartopy
    - matplotlib-base
    - numpy
    - obspy
    - pandas
    - pyproj
    - python >=3.7
    - python-dateutil
    - scipy

test:
  imports:
    - csep
    - csep.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCECCode/pycsep
  summary: Python tools from the Collaboratory for the Study of Earthquake Predictability
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - billtr0n
